language: rust
rust:
  - stable
  - beta
  - nightly

install:
  - sudo apt-get install python-unittest2
  - sudo pip install ghp-import urllib3[secure] autobahntestsuite

before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - sudo apt-get install libssl-dev

script:
  - cargo check
  - cargo check --features async-tls
  - cargo check --features async-std-runtime,async-tls
  - cargo check --features async-std-runtime,async-native-tls
  - cargo check --features async-std-runtime,async-tls,async-native-tls
  - cargo check --features tokio-runtime,async-tls
  - cargo check --features tokio-runtime,tokio-native-tls
  - cargo check --features tokio-runtime,async-tls,tokio-native-tls
  - cargo check --features gio-runtime
  - cargo check --features gio-runtime,async-tls
  - cargo check --features async-std-runtime,async-tls,async-native-tls,tokio-runtime,tokio-native-tls,gio-runtime
  - cargo test --features async-std-runtime
  - sudo apt-get install python-unittest2
  - sudo pip install ghp-import urllib3[secure] autobahntestsuite
  - echo "Running Autobahn TestSuite for client" && ./scripts/autobahn-client.sh
  - echo "Running Autobahn TestSuite for server" && ./scripts/autobahn-server.sh
